### ISSUE TITLE
blender 3.5

### ISSUE THREAD

**Issue by ekswathi** [EMilla6535/bezier_surface#1]
why still blender 2.75?

**Comment by EMilla6535** [comment]
I still use 2.75 version for modelling because I find the new interface very uncomfortable for me. I'm going to update it as soon as I solve some compatibility issues.
Sorry for the late answer I was busy.

**Comment by BUGProtectionAssociation** [comment]
I am waiting for you!
It broken in 3.5+

> 我仍然使用 2.75 版本进行建模，因为我发现新界面对我来说非常不舒服。一旦我解决了一些兼容性问题，我将立即更新它。对不起，回答晚了，我很忙。

<log>
```
Python: Traceback (most recent call last):
  File "G:\blenderplus\3.0\addons\bezier_surface\__init__.py", line 145, in execute
    main(self, obj, context)
  File "G:\blenderplus\3.0\addons\bezier_surface\__init__.py", line 103, in main
    s_name = bezier_func.bezierSurface(x, y, z, t_points, obj.location)
  File "G:\blenderplus\3.0\addons\bezier_surface\bezier_func.py", line 169, in bezierSurface
    s_name = renderBlenderData(r_verts, [], r_faces, "Surface", location)
  File "G:\blenderplus\3.0\addons\bezier_surface\bezier_func.py", line 43, in renderBlenderData
    col.objects.link(obj)
AttributeError: 'NoneType' object has no attribute 'objects'

```
</log>

**Comment by BUGProtectionAssociation** [comment]
> I still use 2.75 version for modelling because I find the new interface very uncomfortable for me. I'm going to update it as soon as I solve some compatibility issues. Sorry for the late answer I was busy.

I am waiting for you!
It broken in 3.5+

<LOG>

```
Python: Traceback (most recent call last):
  File "G:\blenderplus\3.0\addons\bezier_surface\__init__.py", line 145, in execute
    main(self, obj, context)
  File "G:\blenderplus\3.0\addons\bezier_surface\__init__.py", line 103, in main
    s_name = bezier_func.bezierSurface(x, y, z, t_points, obj.location)
  File "G:\blenderplus\3.0\addons\bezier_surface\bezier_func.py", line 169, in bezierSurface
    s_name = renderBlenderData(r_verts, [], r_faces, "Surface", location)
  File "G:\blenderplus\3.0\addons\bezier_surface\bezier_func.py", line 43, in renderBlenderData
    col.objects.link(obj)
AttributeError: 'NoneType' object has no attribute 'objects'

```

</LOG>

**Comment by EMilla6535** [comment]
> 

Can you give me more details about how that error was produced?

**Comment by BUGProtectionAssociation** [comment]
> > 
> 
> Can you give me more details about how that error was produced?

![image](https://github.com/EMilla6535/bezier_surface/assets/65578116/cb8a89e1-b12f-4e32-8994-e88c7e45a74c)

**Comment by BUGProtectionAssociation** [comment]
> I've updated the 3.4 version. If the problem persist, maybe you can post a step by step guide on how to reproduce it, or a sample file so I can check it, because I can't find any problem on my side.

![image](https://github.com/EMilla6535/bezier_surface/assets/65578116/f24d83b8-279c-4b84-995d-f43bd57bbad3)

Create Bezier sure.
![image](https://github.com/EMilla6535/bezier_surface/assets/65578116/da5df5d6-0523-4f2f-ba71-b6238980d9d6)

When add surface
![image](https://github.com/EMilla6535/bezier_surface/assets/65578116/37fa76ef-18c3-477c-b9ec-69790ca398cd)

failed

```
Python: Traceback (most recent call last):
  File "G:\blenderplus\3.0\addons\bezier\__init__.py", line 143, in execute
    main(self, obj, context)
  File "G:\blenderplus\3.0\addons\bezier\__init__.py", line 103, in main
    s_name = bezier_func.bezierSurface(x, y, z, t_points, obj.location)
  File "G:\blenderplus\3.0\addons\bezier\bezier_func.py", line 169, in bezierSurface
    s_name = renderBlenderData(r_verts, [], r_faces, "Surface", location)
  File "G:\blenderplus\3.0\addons\bezier\bezier_func.py", line 43, in renderBlenderData
    col.objects.link(obj)
AttributeError: 'NoneType' object has no attribute 'objects'

```

**Comment by EMilla6535** [comment]
I think I fixed it.
There where problems when the border was outside of a collection. Now it should be OK.
